package com.wenzhi.novel.mysql.model;

import java.util.Date;

public class CS_GameSeries {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CS_GameSeries.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CS_GameSeries.SerieName
     *
     * @mbggenerated
     */
    private String seriename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CS_GameSeries.CPName
     *
     * @mbggenerated
     */
    private String cpname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CS_GameSeries.GameKey
     *
     * @mbggenerated
     */
    private String gamekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CS_GameSeries.MonitorState
     *
     * @mbggenerated
     */
    private Integer monitorstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CS_GameSeries.AutoProState
     *
     * @mbggenerated
     */
    private Integer autoprostate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CS_GameSeries.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CS_GameSeries.ID
     *
     * @return the value of CS_GameSeries.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CS_GameSeries.ID
     *
     * @param id the value for CS_GameSeries.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CS_GameSeries.SerieName
     *
     * @return the value of CS_GameSeries.SerieName
     *
     * @mbggenerated
     */
    public String getSeriename() {
        return seriename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CS_GameSeries.SerieName
     *
     * @param seriename the value for CS_GameSeries.SerieName
     *
     * @mbggenerated
     */
    public void setSeriename(String seriename) {
        this.seriename = seriename == null ? null : seriename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CS_GameSeries.CPName
     *
     * @return the value of CS_GameSeries.CPName
     *
     * @mbggenerated
     */
    public String getCpname() {
        return cpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CS_GameSeries.CPName
     *
     * @param cpname the value for CS_GameSeries.CPName
     *
     * @mbggenerated
     */
    public void setCpname(String cpname) {
        this.cpname = cpname == null ? null : cpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CS_GameSeries.GameKey
     *
     * @return the value of CS_GameSeries.GameKey
     *
     * @mbggenerated
     */
    public String getGamekey() {
        return gamekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CS_GameSeries.GameKey
     *
     * @param gamekey the value for CS_GameSeries.GameKey
     *
     * @mbggenerated
     */
    public void setGamekey(String gamekey) {
        this.gamekey = gamekey == null ? null : gamekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CS_GameSeries.MonitorState
     *
     * @return the value of CS_GameSeries.MonitorState
     *
     * @mbggenerated
     */
    public Integer getMonitorstate() {
        return monitorstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CS_GameSeries.MonitorState
     *
     * @param monitorstate the value for CS_GameSeries.MonitorState
     *
     * @mbggenerated
     */
    public void setMonitorstate(Integer monitorstate) {
        this.monitorstate = monitorstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CS_GameSeries.AutoProState
     *
     * @return the value of CS_GameSeries.AutoProState
     *
     * @mbggenerated
     */
    public Integer getAutoprostate() {
        return autoprostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CS_GameSeries.AutoProState
     *
     * @param autoprostate the value for CS_GameSeries.AutoProState
     *
     * @mbggenerated
     */
    public void setAutoprostate(Integer autoprostate) {
        this.autoprostate = autoprostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CS_GameSeries.CreateTime
     *
     * @return the value of CS_GameSeries.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CS_GameSeries.CreateTime
     *
     * @param createtime the value for CS_GameSeries.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}