package com.wenzhi.novel.mysql.model;

import java.util.Date;

public class PG_MediaStorage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_MediaStorage.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_MediaStorage.MediaType
     *
     * @mbggenerated
     */
    private Integer mediatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_MediaStorage.MediaName
     *
     * @mbggenerated
     */
    private String medianame;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_MediaStorage.DomainPath
     *
     * @mbggenerated
     */
    private String domainpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_MediaStorage.DirPath
     *
     * @mbggenerated
     */
    private String dirpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_MediaStorage.OriginalName
     *
     * @mbggenerated
     */
    private String originalname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_MediaStorage.UserId
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_MediaStorage.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_MediaStorage.UpdateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_MediaStorage.IsDeleted
     *
     * @mbggenerated
     */
    private Byte isdeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_MediaStorage.Id
     *
     * @return the value of PG_MediaStorage.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_MediaStorage.Id
     *
     * @param id the value for PG_MediaStorage.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_MediaStorage.MediaType
     *
     * @return the value of PG_MediaStorage.MediaType
     *
     * @mbggenerated
     */
    public Integer getMediatype() {
        return mediatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_MediaStorage.MediaType
     *
     * @param mediatype the value for PG_MediaStorage.MediaType
     *
     * @mbggenerated
     */
    public void setMediatype(Integer mediatype) {
        this.mediatype = mediatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_MediaStorage.MediaName
     *
     * @return the value of PG_MediaStorage.MediaName
     *
     * @mbggenerated
     */
    public String getMedianame() {
        return medianame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_MediaStorage.MediaName
     *
     * @param medianame the value for PG_MediaStorage.MediaName
     *
     * @mbggenerated
     */
    public void setMedianame(String medianame) {
        this.medianame = medianame == null ? null : medianame.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_MediaStorage.DomainPath
     *
     * @return the value of PG_MediaStorage.DomainPath
     *
     * @mbggenerated
     */
    public String getDomainpath() {
        return domainpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_MediaStorage.DomainPath
     *
     * @param domainpath the value for PG_MediaStorage.DomainPath
     *
     * @mbggenerated
     */
    public void setDomainpath(String domainpath) {
        this.domainpath = domainpath == null ? null : domainpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_MediaStorage.DirPath
     *
     * @return the value of PG_MediaStorage.DirPath
     *
     * @mbggenerated
     */
    public String getDirpath() {
        return dirpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_MediaStorage.DirPath
     *
     * @param dirpath the value for PG_MediaStorage.DirPath
     *
     * @mbggenerated
     */
    public void setDirpath(String dirpath) {
        this.dirpath = dirpath == null ? null : dirpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_MediaStorage.OriginalName
     *
     * @return the value of PG_MediaStorage.OriginalName
     *
     * @mbggenerated
     */
    public String getOriginalname() {
        return originalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_MediaStorage.OriginalName
     *
     * @param originalname the value for PG_MediaStorage.OriginalName
     *
     * @mbggenerated
     */
    public void setOriginalname(String originalname) {
        this.originalname = originalname == null ? null : originalname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_MediaStorage.UserId
     *
     * @return the value of PG_MediaStorage.UserId
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_MediaStorage.UserId
     *
     * @param userid the value for PG_MediaStorage.UserId
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_MediaStorage.CreateTime
     *
     * @return the value of PG_MediaStorage.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_MediaStorage.CreateTime
     *
     * @param createtime the value for PG_MediaStorage.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_MediaStorage.UpdateTime
     *
     * @return the value of PG_MediaStorage.UpdateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_MediaStorage.UpdateTime
     *
     * @param updatetime the value for PG_MediaStorage.UpdateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_MediaStorage.IsDeleted
     *
     * @return the value of PG_MediaStorage.IsDeleted
     *
     * @mbggenerated
     */
    public Byte getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_MediaStorage.IsDeleted
     *
     * @param isdeleted the value for PG_MediaStorage.IsDeleted
     *
     * @mbggenerated
     */
    public void setIsdeleted(Byte isdeleted) {
        this.isdeleted = isdeleted;
    }
}