package com.wenzhi.novel.mysql.model;

import java.util.Date;

public class PG_NovelList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_NovelList.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_NovelList.NovelName
     *
     * @mbggenerated
     */
    private String novelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_NovelList.NovelDesc
     *
     * @mbggenerated
     */
    private String noveldesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_NovelList.NovelAuthor
     *
     * @mbggenerated
     */
    private String novelauthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_NovelList.NovelImage
     *
     * @mbggenerated
     */
    private String novelimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_NovelList.NovelStatus
     *
     * @mbggenerated
     */
    private Byte novelstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_NovelList.IsShow
     *
     * @mbggenerated
     */
    private Byte isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_NovelList.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_NovelList.UpdateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PG_NovelList.IsDeleted
     *
     * @mbggenerated
     */
    private Byte isdeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_NovelList.Id
     *
     * @return the value of PG_NovelList.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_NovelList.Id
     *
     * @param id the value for PG_NovelList.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_NovelList.NovelName
     *
     * @return the value of PG_NovelList.NovelName
     *
     * @mbggenerated
     */
    public String getNovelname() {
        return novelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_NovelList.NovelName
     *
     * @param novelname the value for PG_NovelList.NovelName
     *
     * @mbggenerated
     */
    public void setNovelname(String novelname) {
        this.novelname = novelname == null ? null : novelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_NovelList.NovelDesc
     *
     * @return the value of PG_NovelList.NovelDesc
     *
     * @mbggenerated
     */
    public String getNoveldesc() {
        return noveldesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_NovelList.NovelDesc
     *
     * @param noveldesc the value for PG_NovelList.NovelDesc
     *
     * @mbggenerated
     */
    public void setNoveldesc(String noveldesc) {
        this.noveldesc = noveldesc == null ? null : noveldesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_NovelList.NovelAuthor
     *
     * @return the value of PG_NovelList.NovelAuthor
     *
     * @mbggenerated
     */
    public String getNovelauthor() {
        return novelauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_NovelList.NovelAuthor
     *
     * @param novelauthor the value for PG_NovelList.NovelAuthor
     *
     * @mbggenerated
     */
    public void setNovelauthor(String novelauthor) {
        this.novelauthor = novelauthor == null ? null : novelauthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_NovelList.NovelImage
     *
     * @return the value of PG_NovelList.NovelImage
     *
     * @mbggenerated
     */
    public String getNovelimage() {
        return novelimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_NovelList.NovelImage
     *
     * @param novelimage the value for PG_NovelList.NovelImage
     *
     * @mbggenerated
     */
    public void setNovelimage(String novelimage) {
        this.novelimage = novelimage == null ? null : novelimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_NovelList.NovelStatus
     *
     * @return the value of PG_NovelList.NovelStatus
     *
     * @mbggenerated
     */
    public Byte getNovelstatus() {
        return novelstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_NovelList.NovelStatus
     *
     * @param novelstatus the value for PG_NovelList.NovelStatus
     *
     * @mbggenerated
     */
    public void setNovelstatus(Byte novelstatus) {
        this.novelstatus = novelstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_NovelList.IsShow
     *
     * @return the value of PG_NovelList.IsShow
     *
     * @mbggenerated
     */
    public Byte getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_NovelList.IsShow
     *
     * @param isshow the value for PG_NovelList.IsShow
     *
     * @mbggenerated
     */
    public void setIsshow(Byte isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_NovelList.CreateTime
     *
     * @return the value of PG_NovelList.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_NovelList.CreateTime
     *
     * @param createtime the value for PG_NovelList.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_NovelList.UpdateTime
     *
     * @return the value of PG_NovelList.UpdateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_NovelList.UpdateTime
     *
     * @param updatetime the value for PG_NovelList.UpdateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PG_NovelList.IsDeleted
     *
     * @return the value of PG_NovelList.IsDeleted
     *
     * @mbggenerated
     */
    public Byte getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PG_NovelList.IsDeleted
     *
     * @param isdeleted the value for PG_NovelList.IsDeleted
     *
     * @mbggenerated
     */
    public void setIsdeleted(Byte isdeleted) {
        this.isdeleted = isdeleted;
    }
}