package com.wenzhi.novel.mysql.dao;

import com.wenzhi.novel.mysql.model.CS_GameSerieList;
import com.wenzhi.novel.mysql.model.CS_GameSerieListExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CS_GameSerieListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_GameSerieList
     *
     * @mbggenerated
     */
    int countByExample(CS_GameSerieListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_GameSerieList
     *
     * @mbggenerated
     */
    int deleteByExample(CS_GameSerieListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_GameSerieList
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_GameSerieList
     *
     * @mbggenerated
     */
    int insert(CS_GameSerieList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_GameSerieList
     *
     * @mbggenerated
     */
    int insertSelective(CS_GameSerieList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_GameSerieList
     *
     * @mbggenerated
     */
    List<CS_GameSerieList> selectByExample(CS_GameSerieListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_GameSerieList
     *
     * @mbggenerated
     */
    CS_GameSerieList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_GameSerieList
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CS_GameSerieList record, @Param("example") CS_GameSerieListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_GameSerieList
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CS_GameSerieList record, @Param("example") CS_GameSerieListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_GameSerieList
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CS_GameSerieList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CS_GameSerieList
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CS_GameSerieList record);
}