package com.wenzhi.novel.mysql.dao;

import com.wenzhi.novel.mysql.model.PG_MediaStorage;
import com.wenzhi.novel.mysql.model.PG_MediaStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PG_MediaStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_MediaStorage
     *
     * @mbggenerated
     */
    int countByExample(PG_MediaStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_MediaStorage
     *
     * @mbggenerated
     */
    int deleteByExample(PG_MediaStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_MediaStorage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_MediaStorage
     *
     * @mbggenerated
     */
    int insert(PG_MediaStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_MediaStorage
     *
     * @mbggenerated
     */
    int insertSelective(PG_MediaStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_MediaStorage
     *
     * @mbggenerated
     */
    List<PG_MediaStorage> selectByExample(PG_MediaStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_MediaStorage
     *
     * @mbggenerated
     */
    PG_MediaStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_MediaStorage
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PG_MediaStorage record, @Param("example") PG_MediaStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_MediaStorage
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PG_MediaStorage record, @Param("example") PG_MediaStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_MediaStorage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PG_MediaStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_MediaStorage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PG_MediaStorage record);
}