package com.wenzhi.novel.mysql.dao;

import com.wenzhi.novel.mysql.model.PG_NovelList;
import com.wenzhi.novel.mysql.model.PG_NovelListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PG_NovelListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_NovelList
     *
     * @mbggenerated
     */
    int countByExample(PG_NovelListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_NovelList
     *
     * @mbggenerated
     */
    int deleteByExample(PG_NovelListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_NovelList
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_NovelList
     *
     * @mbggenerated
     */
    int insert(PG_NovelList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_NovelList
     *
     * @mbggenerated
     */
    int insertSelective(PG_NovelList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_NovelList
     *
     * @mbggenerated
     */
    List<PG_NovelList> selectByExample(PG_NovelListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_NovelList
     *
     * @mbggenerated
     */
    PG_NovelList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_NovelList
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PG_NovelList record, @Param("example") PG_NovelListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_NovelList
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PG_NovelList record, @Param("example") PG_NovelListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_NovelList
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PG_NovelList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PG_NovelList
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PG_NovelList record);
}