server:
  port: 8080

management:
  port: 8090

spring:
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  druid:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.199.5.223:3306/lovenovel?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 'CHEN#mysql&369'
    maxActive: 10
    minIdle: 5
    maxWait: 10000
    validationQuery: SELECT '1'
  redis:
    cache:
      clusterNodes: 139.199.5.223:6379
      commandTimeout: 5000

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.shenqi.chatcs.model  # 注意：对应实体类的路径
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
